name: Deploy to Google Cloud Storage
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install dependences
        run: npm install

      - name: build
        run: npm run build

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Google Cloud Storage
        run: gsutil -m rsync -R ./build gs://${{ secrets.GCS_BUCKET_NAME }}

      - name: allow public access
        run: gsutil -m acl ch -R -u AllUsers:R gs://${{ secrets.GCS_BUCKET_NAME }}

      - name: cache control
        run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://${{ secrets.GCS_BUCKET_NAME }}/**/*.{png,svg,css,js}

      - name: cache control
        run: gsutil -m setmeta -h "Cache-Control:no-cache, no-store" gs://${{ secrets.GCS_BUCKET_NAME }}/index.html